cp.o: cp.cc cp.h
benchmark.o: ../cp-common/benchmark.cc ../common/error.h \
 ../common/timer.h cp.h
test.o: ../cp-common/test.cc cp.h ../common/error.h
error.o: ../common/error.cc ../common/error.h
mm.o: main.cpp cp.cc cp.h base.cc debug.cpp